package prupoc.newbusiness;

import java.math.BigDecimal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SumAssured implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Type")
   private java.lang.String type;
   @org.kie.api.definition.type.Label("Value")
   private BigDecimal value;
   @org.kie.api.definition.type.Label("Currency")
   private java.lang.String currency;

   public SumAssured()
   {
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public java.lang.String getCurrency()
   {
      return this.currency;
   }

   public void setCurrency(java.lang.String currency)
   {
      this.currency = currency;
   }

   public java.math.BigDecimal getValue()
   {
      return this.value;
   }

   public void setValue(java.math.BigDecimal value)
   {
      this.value = value;
   }

   public SumAssured(java.lang.String type, java.math.BigDecimal value,
         java.lang.String currency)
   {
      this.type = type;
      this.value = value;
      this.currency = currency;
   }

@Override
public String toString() {
	return "SumAssured [type=" + type + ", value=" + value + ", currency="
			+ currency + "]";
}

   
   
   
}